// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Candle: typeof import('./components/Candle.vue')['default']
    CarbonChartClusterBar: typeof import('~icons/carbon/chart-cluster-bar')['default']
    CarbonDataBase: typeof import('~icons/carbon/data-base')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonPaintBrush: typeof import('~icons/carbon/paint-brush')['default']
    Card: typeof import('./components/Card.vue')['default']
    Cell: typeof import('./components/Cell.vue')['default']
    CellGroup: typeof import('./components/CellGroup.vue')['default']
    ChartCountPerDate: typeof import('./components/chart-count-per-date.vue')['default']
    ChartCountPerDay: typeof import('./components/chart-count-per-day.vue')['default']
    ChartCountPerDistrict: typeof import('./components/chart-count-per-district.vue')['default']
    ChartCountPerHour: typeof import('./components/chart-count-per-hour.vue')['default']
    ChartCountPerMonth: typeof import('./components/chart-count-per-month.vue')['default']
    ChartCountPerWeek: typeof import('./components/chart-count-per-week.vue')['default']
    List: typeof import('./components/List.vue')['default']
    RomanticBulb: typeof import('./components/RomanticBulb.vue')['default']
    RomanticCandle: typeof import('./components/RomanticCandle.vue')['default']
    SiteFooter: typeof import('./components/site-footer.vue')['default']
  }
}

export { }
