// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Branding: typeof import('./components/Branding.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CovidChart: typeof import('./components/CovidChart.vue')['default']
    'CovidChart copy': typeof import('./components/CovidChart copy.vue')['default']
    DashboardSidebar: typeof import('./components/DashboardSidebar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Footer copy': typeof import('./components/Footer copy.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    'Logo copy': typeof import('./components/Logo copy.vue')['default']
    ReactiveCovidChart: typeof import('./components/ReactiveCovidChart.vue')['default']
    README: typeof import('./components/README.md')['default']
    SampleChart: typeof import('./components/SampleChart.vue')['default']
    'SampleChart copy': typeof import('./components/SampleChart copy.vue')['default']
    SidebarUserMenu: typeof import('./components/SidebarUserMenu.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}

export { }
