// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Candle: typeof import('./components/Candle.vue')['default']
    Cell: typeof import('./components/Cell.vue')['default']
    CellGroup: typeof import('./components/CellGroup.vue')['default']
    List: typeof import('./components/List.vue')['default']
    RomanticCandle: typeof import('./components/RomanticCandle.vue')['default']
  }
}

export { }
